### ISSUE TITLE
Typedef enum syntax error on STM32

### ISSUE THREAD

**Issue by DellyMore** [udik-chudik/SI4432#1]
SI4432_constants.h  all typedef enum with binary literal compilation error

example

typedef enum {
    SI44_PH_PATH_OFF     = 0b00000000,
    SI44_PH_PATH_RX_ONLY = 0b10000000,
    SI44_PH_PATH_TX_ONLY = 0b00001000,
    SI44_PH_PATH_TXRX = (SI44_PH_PATH_RX_ONLY | SI44_PH_PATH_TX_ONLY)
}SI44_PH_PATH;

IAR workbench result traceroute:
Error[Pe067]: expected a "}"

**Comment by udik-chudik** [comment]
Hello! Unfortunately I have not tested this lib in IAR workbench, only in gcc toolchain. I think this error caused by `0b` literal in constants definition like [said here](https://stackoverflow.com/questions/68891165/typedef-enum-with-binary-definitions-error-iar-8-40). You could try to change constants from binary representation to decimal and try to compile in that manner.

**Comment by DellyMore** [comment]
Thank you!
